version: '3'

services:
  mysql:
    image: mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=fuawb.cJAIO.o619eD8.X45.zPwov333fwe
      - MYSQL_DATABASE=svc